# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccr_number', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Complete', 'Complete')], default='Open', max_length=15)),
                ('technology_type', models.CharField(choices=[('Vmware', 'Vmware'), ('Windows Server 2008', 'Windows Server 2008'), ('Windows Server 2012', 'Windows Server 2012'), ('F5 GTM', 'F5 GTM'), ('F5 LTM', 'F5 LTM'), ('Cisco Switch', 'Cisco Switch'), ('Checkpoint Firewall', 'Checkpoint Firewall'), ('Cisco Wireless', 'Cisco Wireless'), ('3 Par Storage', '3 Par Storage'), ('HP Storage', 'HP Storage'), ('ISCSI Switch', 'ISCSI Switch'), ('Tape Backup', 'Tape Backup'), ('ILO', 'ILO'), ('Brocade', 'Brocade'), ('Linux', 'Linux'), ('AWS', 'AWS'), ('Apache', 'Apache'), ('Anti Virus', 'Anti Virus'), ('ESX Host', 'ESX Host'), ('Physical Host', 'Physical Host'), ('NIC', 'NIC'), ('Windows SQL Server', 'Windows SQL Server'), ('Application', 'Application'), ('SFTP Server Software', 'SFTP Server Software')], max_length=20)),
                ('device_app', models.CharField(choices=[('Device', 'Device'), ('Application', 'Application')], max_length=15)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('date_of_change', models.DateField()),
                ('reason', models.TextField()),
                ('roll_back_plan', models.TextField()),
                ('is_downtime', models.BooleanField(default=False)),
                ('downtime_duration', models.CharField(max_length=120)),
                ('time_to_change', models.CharField(max_length=120)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=4)),
                ('users_affected', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('Cork', 'Cork'), ('Dublin', 'Dublin')], max_length=6)),
                ('date_of_review', models.DateField(null=True)),
                ('comments_r', models.TextField(null=True)),
                ('date_approved', models.DateField(null=True)),
                ('comments_a', models.TextField(null=True)),
                ('completion_date', models.DateField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominated_approver', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completer', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('implamenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_implamenter', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominated_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_at_rev', models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Complete', 'Complete')], default='Open', max_length=15)),
                ('date', models.DateField()),
                ('ccr_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccrform.Ccr')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
