# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='device_app',
            field=models.CharField(choices=[('Device', 'Device'), ('Application', 'Application')], max_length=15, verbose_name='Device or Application'),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='is_downtime',
            field=models.BooleanField(default=False, verbose_name='Is there Downtime'),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Is this Standard Maintenance'),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Complete', 'Complete')], default='Open', max_length=15),
        ),
        migrations.AlterField(
            model_name='ccr',
            name='users_affected',
            field=models.BooleanField(default=False, verbose_name='Are Users Affected?'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status_at_rev',
            field=models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Complete', 'Complete')], default='Open', max_length=15),
        ),
    ]
