# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0002_auto_20160208_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='risk',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=8),
        ),
    ]
