# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0003_auto_20160208_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rejected for Amendments', 'Rejected for Amendments'), ('Complete', 'Complete')], default='Open', max_length=15),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status_at_rev',
            field=models.CharField(choices=[('Open', 'Open'), ('For Review', 'For Review'), ('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rejected for Amendments', 'Rejected for Amendments'), ('Complete', 'Complete')], default='Open', max_length=15),
        ),
    ]
