# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0006_auto_20160224_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='downtime_duration',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
