# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0007_auto_20160225_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='reviewer',
            field=models.ForeignKey(default='Vincent', on_delete=django.db.models.deletion.CASCADE, related_name='nominated_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
