# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrform', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccr',
            name='downtime_duration',
            field=models.CharField(blank=True, default='0', max_length=120),
        ),
    ]
